import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";

const geistMono = Exo_2({
  variable: "--font-exo-2",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Glow Line Discover",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistMono.variable} antialiased bg-amber-200`}
      >
        {children}
      </body>
    </html>
  );
}
